language: java
jdk:
- openjdk11
branches:
  only:
  - main
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"

before_install:
  - openssl aes-256-cbc -K $encrypted_dd868b5a6e58_key -iv $encrypted_dd868b5a6e58_iv -in application-dev.yml.enc -out application-dev.yml -d
  - chmod +x gradlew


before_deploy:
  # 현재 위치의 모든 파일을 springboot-test 압축한다.
  - zip -r springboot-test *
  # deploy 디렉토리를 Travis가 실행 중인 위치에 생성한다.
  - mkdir -p deploy
  # 생성한 .zip 파일을 deploy 아래로 이동한다
  - mv springboot-test.zip deploy/springboot-test.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    #s3 버킷 이름
    bucket: yushin09
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리로 이동한다. 해당 위치의 파일만 이동시킨다.
    wait-unil-deployed: true
    on:
      branch: main



notifications:
  email:
    recipients:
    - kkad45@naver.com
