version: 0.0
os: linux
files:
  - source: /
    destination: /home/git/simpleMarket
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    # EC2경로가 아니라 배포할 소스 코드에 shell script가 있어야 함에 유의!!
    - location: script/deploy.sh
      runas: root