version: 0.0
os: linux
files:
  - source: / #  source 명령은 인스턴스에 복사할 개정의 파일 또는 디렉터리를 식별합니다. 디렉터리를 나타내는 경우 디렉터리의 모든파일 복사
    destination: /home/git/simpleMarket2 #  인스턴스에서 파일이 복사되어야 하는 위치를 식별합니다. /root/destination/directory(Linux, RHEL, Ubuntu) 정규화된 주소
    overwrite: yes # OVERWRITE: 현재 배포 중인 애플리케이션 개정 버전의 파일 버전이 인스턴스에 이미 있는 버전을 대체합니다.

# deploy 이후 권한설정을 할 수 있다.
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777

#인플레이스 배포
hooks:
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링부트 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링부투를 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 스프링부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user
