version: 0.0
os: linux
files:
  - source: /
    destination: /home/git/simpleMarket
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: /script/deploy.sh
      timeout: 60
      runas: ec2-user
