spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB
  profiles:
    include: "dev"

logging:
  level:
    me.silvernine: DEBUG
    org:
      hibernate:
        type: trace

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

