spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB
  profiles:
    include: "dev"
    group:
      "real1": "real1"
      "real2": "real2"


logging:
  level:
    me.silvernine: DEBUG
    org:
      hibernate:
        type: trace

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

---
spring:
  config:
    activate:
      on-profile: "real1"
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: "real2"
server:
  port: 8082

